name: Ping Supabase

on:
  schedule:
    - cron: '0 10 */3 * *' # every 3 days at 10:00 UTC
  workflow_dispatch: # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: backlogtracker

      - name: Run Supabase Ping Script
        run: node scripts/ping-supabase.mjs
        # working-directory: backlogtracker
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
